In [1]:
%pip install torch

     ------------------------------------- 167.3/167.3 MB 13.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import torch

c:\Users\ACER\anaconda3\envs\testing1\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
SEED = 1234  # To reproduce same results    

In [6]:
np.random.seed(SEED)
torch.manual_seed(SEED)

In [9]:
x = torch.randn(2,3)
print(f"type is {type(x)}")
print(f"type is {x.type()}")
print(x.shape)
print(x)


type is <class 'torch.Tensor'>
type is torch.FloatTensor
torch.Size([2, 3])
tensor([[-0.1549, -1.3706, -0.1319],
        [ 0.8848, -0.2611,  0.6104]])


In [11]:
x = torch.zeros(2,3)

#x = torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
x = torch.Tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [14]:
#Reshape
x= torch.randn(2,3)
y =x.view(3,2)
print(y.shape)


torch.Size([3, 2])


In [25]:
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])

print(x)
print(x.size(0))
print(x.size(1))
print(x.size(2))


a = x.view(x.size(1),-1)  # -1 flattens the array, here 3,-1 means 3 will be first dimension and fit the other elements by flatting the array
b=x.view(x.size(2),-1)
print(b.shape)
print(a.shape)


tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])
2
3
4
torch.Size([4, 6])
torch.Size([3, 8])


In [26]:
# Dimensional operations
x = torch.randn(2, 3)
print(f"Values: \n{x}")
y = torch.sum(x, dim=0) # add each row's value for every column

Values: 
tensor([[ 0.1922,  0.0918, -0.8625],
        [ 0.1596,  0.8184, -0.7649]])


In [27]:
#indexing
x = torch.randn(3, 4)
print (f"x: \n{x}")
print (f"x[:1]: \n{x[:1]}")
print (f"x[:1, 1:3]: \n{x[:1, 1:3]}")

x: 
tensor([[ 0.8042, -0.1383,  0.3196, -1.0187],
        [-1.3147,  2.5228,  0.4501,  0.2709],
        [-0.8087, -0.0217, -1.0413,  0.0702]])
x[:1]: 
tensor([[ 0.8042, -0.1383,  0.3196, -1.0187]])
x[:1, 1:3]: 
tensor([[-0.1383,  0.3196]])
